replicaCount: 2

image:
  repository: registry.skauswatch.app/icebox-pki-server
  pullPolicy: Always

ingress:
  host: icebox.skauswatch.app

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  LOG_LEVEL: "warn"
  DB_POOL_SIZE: "10"
