"""Golden parity corpus — replayed in order against v1 (Quart) and v2 (Rust).

Every REST endpoint of all 11 routers is covered with happy-path, auth
failure, validation failure, and role-gate cases. Order is load-bearing:
mutating cases run identically on both sides so DB state stays in lockstep,
and user-count-sensitive cases (free-tier cap) run while the count is < 5.

Case keys:
  id      unique dotted name (allowlist references these)
  method  HTTP method
  path    request path (no host)
  auth    "admin"|"maintainer"|"viewer"|"none"|"invalid"|"basic"|
          "refresh-as-access"|"ctx:<NAME>"|"agent:<agent_id>"|
          "agentbad:<agent_id>"|"agentmissing"
  json    optional JSON body; string values exactly "$NAME" are replaced
          from the per-side context (values captured via `save`)
  raw_json optional raw string body sent with JSON content-type
  query   optional raw query string
  files   optional dict for multipart upload {field: (filename, bytes)}
  save    optional {ctx_name: dotted.path} captured from the response JSON
"""

SEED_PASSWORD = "Password123!"

CASES = [
    # ── root / health ────────────────────────────────────────────────────
    {"id": "root.healthz", "method": "GET", "path": "/healthz", "auth": "none"},
    {"id": "root.readyz", "method": "GET", "path": "/readyz", "auth": "none"},
    {"id": "root.version", "method": "GET", "path": "/version", "auth": "none"},
    {"id": "root.unknown-route", "method": "GET", "path": "/api/v1/nope", "auth": "admin"},

    # ── auth ─────────────────────────────────────────────────────────────
    {"id": "auth.login.happy-admin", "sleep_before": 1.1, "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "admin@skauswatch.dev", "password": SEED_PASSWORD}},
    {"id": "auth.login.val-bad-email", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "not-an-email", "password": "x"}},
    {"id": "auth.login.val-empty-password", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "admin@skauswatch.dev", "password": ""}},
    {"id": "auth.login.unknown-email", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "ghost@skauswatch.dev", "password": "whatever1"}},
    {"id": "auth.login.inactive-correct-pw", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "inactive@skauswatch.dev", "password": SEED_PASSWORD}},
    {"id": "auth.login.inactive-wrong-pw", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "inactive@skauswatch.dev", "password": "wrongpassword"}},

    {"id": "auth.me.admin", "method": "GET", "path": "/api/v1/auth/me", "auth": "admin"},
    {"id": "auth.me.viewer", "method": "GET", "path": "/api/v1/auth/me", "auth": "viewer"},
    {"id": "auth.me.no-token", "method": "GET", "path": "/api/v1/auth/me", "auth": "none"},
    {"id": "auth.me.invalid-token", "method": "GET", "path": "/api/v1/auth/me", "auth": "invalid"},
    {"id": "auth.me.basic-scheme", "method": "GET", "path": "/api/v1/auth/me", "auth": "basic"},
    {"id": "auth.me.refresh-as-access", "method": "GET", "path": "/api/v1/auth/me", "auth": "refresh-as-access"},

    # refresh rotation flow (dedicated login so token bookkeeping is visible)
    {"id": "auth.refresh.setup-login", "sleep_before": 1.1, "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "viewer@skauswatch.dev", "password": SEED_PASSWORD},
     "save": {"R1": "refresh_token"}},
    {"id": "auth.refresh.happy", "sleep_before": 1.1, "method": "POST", "path": "/api/v1/auth/refresh", "auth": "none",
     "json": {"refresh_token": "$R1"}, "save": {"R2": "refresh_token"}},
    {"id": "auth.refresh.reuse-revoked", "method": "POST", "path": "/api/v1/auth/refresh", "auth": "none",
     "json": {"refresh_token": "$R1"}},
    {"id": "auth.refresh.garbage-token", "method": "POST", "path": "/api/v1/auth/refresh", "auth": "none",
     "json": {"refresh_token": "not.a.jwt"}},
    {"id": "auth.refresh.access-as-refresh", "method": "POST", "path": "/api/v1/auth/refresh", "auth": "none",
     "json": {"refresh_token": "$ADMIN_ACCESS"}},
    {"id": "auth.refresh.val-missing-field", "method": "POST", "path": "/api/v1/auth/refresh", "auth": "none",
     "json": {}},

    # viewer now has: setup token (runner), R1 (revoked), R2 → logout counts
    {"id": "auth.logout.viewer", "method": "POST", "path": "/api/v1/auth/logout", "auth": "viewer"},
    {"id": "auth.me.after-logout", "method": "GET", "path": "/api/v1/auth/me", "auth": "viewer"},
    {"id": "auth.logout.no-token", "method": "POST", "path": "/api/v1/auth/logout", "auth": "none"},

    # ── users (user count is 4 here — free-tier cap must not trigger) ────
    {"id": "users.list.viewer-403", "method": "GET", "path": "/api/v1/users", "auth": "viewer"},
    {"id": "users.list.maintainer", "method": "GET", "path": "/api/v1/users", "auth": "maintainer"},
    {"id": "users.list.paginated", "method": "GET", "path": "/api/v1/users", "auth": "admin",
     "query": "page=2&per_page=2"},
    {"id": "users.list.per-page-capped", "method": "GET", "path": "/api/v1/users", "auth": "admin",
     "query": "per_page=1000"},
    {"id": "users.list.no-token", "method": "GET", "path": "/api/v1/users", "auth": "none"},
    {"id": "users.get.self-viewer", "method": "GET", "path": "/api/v1/users/3", "auth": "viewer"},
    {"id": "users.get.other-viewer-403", "method": "GET", "path": "/api/v1/users/1", "auth": "viewer"},
    {"id": "users.get.other-maintainer", "method": "GET", "path": "/api/v1/users/1", "auth": "maintainer"},
    {"id": "users.get.404", "method": "GET", "path": "/api/v1/users/999", "auth": "admin"},
    {"id": "users.create.viewer-403", "method": "POST", "path": "/api/v1/users", "auth": "viewer",
     "json": {"email": "x@skauswatch.dev", "password": "Password123!"}},
    {"id": "users.create.val-bad-email", "method": "POST", "path": "/api/v1/users", "auth": "admin",
     "json": {"email": "nope", "password": "Password123!"}},
    {"id": "users.create.val-short-password", "method": "POST", "path": "/api/v1/users", "auth": "admin",
     "json": {"email": "y@skauswatch.dev", "password": "short"}},
    {"id": "users.create.val-bad-role", "method": "POST", "path": "/api/v1/users", "auth": "admin",
     "json": {"email": "z@skauswatch.dev", "password": "Password123!", "role": "root"}},
    {"id": "users.create.duplicate-409", "method": "POST", "path": "/api/v1/users", "auth": "admin",
     "json": {"email": "viewer@skauswatch.dev", "password": "Password123!"}},
    {"id": "users.create.happy", "method": "POST", "path": "/api/v1/users", "auth": "admin",
     "json": {"email": "newuser@skauswatch.dev", "password": "Password123!",
              "full_name": "Nina New", "role": "maintainer"}},
    {"id": "users.update.admin-role-change", "method": "PUT", "path": "/api/v1/users/5", "auth": "admin",
     "json": {"role": "viewer", "full_name": "Nina Renamed"}},
    {"id": "users.update.self-viewer", "method": "PUT", "path": "/api/v1/users/3", "auth": "viewer",
     "json": {"full_name": "Vera V.", "password": "Password123!"}},
    {"id": "users.update.self-role-dropped", "method": "PUT", "path": "/api/v1/users/3", "auth": "viewer",
     "json": {"role": "admin", "is_active": False}},
    {"id": "users.update.other-viewer-403", "method": "PUT", "path": "/api/v1/users/1", "auth": "viewer",
     "json": {"full_name": "nope"}},
    {"id": "users.update.404", "method": "PUT", "path": "/api/v1/users/999", "auth": "admin",
     "json": {"full_name": "ghost"}},
    {"id": "users.update.email-conflict-409", "method": "PUT", "path": "/api/v1/users/5", "auth": "admin",
     "json": {"email": "admin@skauswatch.dev"}},
    {"id": "users.update.val-bad-email", "method": "PUT", "path": "/api/v1/users/3", "auth": "viewer",
     "json": {"email": "not-an-email"}},
    {"id": "users.delete.viewer-403", "method": "DELETE", "path": "/api/v1/users/5", "auth": "viewer"},
    {"id": "users.delete.self-400", "method": "DELETE", "path": "/api/v1/users/1", "auth": "admin"},
    {"id": "users.delete.404", "method": "DELETE", "path": "/api/v1/users/999", "auth": "admin"},
    {"id": "users.delete.happy", "method": "DELETE", "path": "/api/v1/users/5", "auth": "admin"},

    # ── auth.register (count back to 4; register has no cap) ─────────────
    {"id": "auth.register.val-bad-email", "method": "POST", "path": "/api/v1/auth/register", "auth": "none",
     "json": {"email": "nope", "password": "Password123!"}},
    {"id": "auth.register.val-short-password", "method": "POST", "path": "/api/v1/auth/register", "auth": "none",
     "json": {"email": "reg@skauswatch.dev", "password": "short"}},
    {"id": "auth.register.duplicate-409", "method": "POST", "path": "/api/v1/auth/register", "auth": "none",
     "json": {"email": "admin@skauswatch.dev", "password": "Password123!"}},
    {"id": "auth.register.happy", "method": "POST", "path": "/api/v1/auth/register", "auth": "none",
     "json": {"email": "newreg@skauswatch.dev", "password": "Password123!", "full_name": "Rex Register"}},

    # lockout: 5 wrong-password logins on the fresh user, then a correct one
    {"id": "auth.lockout.bad-1", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "newreg@skauswatch.dev", "password": "wrong-1"}},
    {"id": "auth.lockout.bad-2", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "newreg@skauswatch.dev", "password": "wrong-2"}},
    {"id": "auth.lockout.bad-3", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "newreg@skauswatch.dev", "password": "wrong-3"}},
    {"id": "auth.lockout.bad-4", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "newreg@skauswatch.dev", "password": "wrong-4"}},
    {"id": "auth.lockout.bad-5", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "newreg@skauswatch.dev", "password": "wrong-5"}},
    {"id": "auth.lockout.locked-correct-pw", "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "newreg@skauswatch.dev", "password": "Password123!"}},

    # ── alerts ───────────────────────────────────────────────────────────
    {"id": "alerts.list.viewer", "method": "GET", "path": "/api/v1/alerts", "auth": "viewer"},
    {"id": "alerts.list.filter-severity", "method": "GET", "path": "/api/v1/alerts", "auth": "viewer",
     "query": "severity=critical&severity=high"},
    {"id": "alerts.list.filter-status-source", "method": "GET", "path": "/api/v1/alerts", "auth": "viewer",
     "query": "status=resolved&source=manual"},
    {"id": "alerts.list.filter-empty", "method": "GET", "path": "/api/v1/alerts", "auth": "viewer",
     "query": "severity=low"},
    {"id": "alerts.list.paginated", "method": "GET", "path": "/api/v1/alerts", "auth": "viewer",
     "query": "page=2&per_page=2"},
    {"id": "alerts.list.no-token", "method": "GET", "path": "/api/v1/alerts", "auth": "none"},
    {"id": "alerts.get.happy", "method": "GET", "path": "/api/v1/alerts/3", "auth": "viewer"},
    {"id": "alerts.get.404", "method": "GET", "path": "/api/v1/alerts/999", "auth": "viewer"},
    {"id": "alerts.create.viewer-403", "method": "POST", "path": "/api/v1/alerts", "auth": "viewer",
     "json": {"title": "t", "description": "d", "severity": "low", "source": "manual"}},
    {"id": "alerts.create.val-bad-severity", "method": "POST", "path": "/api/v1/alerts", "auth": "admin",
     "json": {"title": "t", "description": "d", "severity": "apocalyptic", "source": "manual"}},
    {"id": "alerts.create.val-missing-description", "method": "POST", "path": "/api/v1/alerts", "auth": "admin",
     "json": {"title": "t", "severity": "low", "source": "manual"}},
    {"id": "alerts.create.happy", "method": "POST", "path": "/api/v1/alerts", "auth": "admin",
     "json": {"title": "Harness alert", "description": "Created by parity corpus",
              "severity": "high", "source": "harness", "indicators": ["203.0.113.7"]}},
    {"id": "alerts.update.maintainer", "method": "PUT", "path": "/api/v1/alerts/5", "auth": "maintainer",
     "json": {"status": "resolved", "resolution_notes": "closed by harness"}},
    {"id": "alerts.update.viewer-403", "method": "PUT", "path": "/api/v1/alerts/1", "auth": "viewer",
     "json": {"title": "nope"}},
    {"id": "alerts.update.404", "method": "PUT", "path": "/api/v1/alerts/999", "auth": "admin",
     "json": {"title": "ghost"}},
    {"id": "alerts.update.val-bad-status", "method": "PUT", "path": "/api/v1/alerts/1", "auth": "admin",
     "json": {"status": "vanished"}},
    # documented defect #7: v1 had NO role gate here; v2 adds admin/maintainer
    {"id": "alerts.status.viewer-defect7", "method": "PUT", "path": "/api/v1/alerts/2/status", "auth": "viewer",
     "json": {"status": "in_progress"}},
    {"id": "alerts.status.admin", "method": "PUT", "path": "/api/v1/alerts/1/status", "auth": "admin",
     "json": {"status": "escalated"}},
    {"id": "alerts.status.invalid-value", "method": "PUT", "path": "/api/v1/alerts/1/status", "auth": "admin",
     "json": {"status": "gone"}},
    {"id": "alerts.status.404", "method": "PUT", "path": "/api/v1/alerts/999/status", "auth": "admin",
     "json": {"status": "resolved"}},
    {"id": "alerts.ai-review.viewer-403", "method": "POST", "path": "/api/v1/alerts/1/ai-review", "auth": "viewer",
     "json": {}},
    {"id": "alerts.ai-review.404", "method": "POST", "path": "/api/v1/alerts/999/ai-review", "auth": "admin",
     "json": {}},
    {"id": "alerts.ai-review.happy", "method": "POST", "path": "/api/v1/alerts/1/ai-review", "auth": "admin",
     "json": {"provider": "claude", "priority": 3}},
    {"id": "alerts.search.by-text", "method": "POST", "path": "/api/v1/alerts/search", "auth": "viewer",
     "json": {"query": "beacon"}},
    {"id": "alerts.search.filters", "method": "POST", "path": "/api/v1/alerts/search", "auth": "viewer",
     "json": {"severity": ["high", "critical"], "status": ["pending", "escalated", "in_progress"], "per_page": 10}},
    {"id": "alerts.search.val-bad-page", "method": "POST", "path": "/api/v1/alerts/search", "auth": "viewer",
     "json": {"page": 0}},
    {"id": "alerts.statistics", "method": "GET", "path": "/api/v1/alerts/statistics", "auth": "viewer"},

    # ── threat-intel ─────────────────────────────────────────────────────
    {"id": "ti.iocs.list", "method": "GET", "path": "/api/v1/threat-intel/iocs", "auth": "viewer"},
    {"id": "ti.iocs.list-include-expired", "method": "GET", "path": "/api/v1/threat-intel/iocs", "auth": "viewer",
     "query": "include_expired=true"},
    {"id": "ti.iocs.list-filters", "method": "GET", "path": "/api/v1/threat-intel/iocs", "auth": "viewer",
     "query": "type=ip&type=domain&threat_level=high"},
    {"id": "ti.iocs.list-source-filter", "method": "GET", "path": "/api/v1/threat-intel/iocs", "auth": "viewer",
     "query": "source=otx"},
    {"id": "ti.iocs.list-per-page-capped", "method": "GET", "path": "/api/v1/threat-intel/iocs", "auth": "viewer",
     "query": "per_page=9999"},
    {"id": "ti.iocs.list.no-token", "method": "GET", "path": "/api/v1/threat-intel/iocs", "auth": "none"},
    {"id": "ti.iocs.get", "method": "GET", "path": "/api/v1/threat-intel/iocs/1", "auth": "viewer"},
    {"id": "ti.iocs.get-404", "method": "GET", "path": "/api/v1/threat-intel/iocs/999", "auth": "viewer"},
    {"id": "ti.iocs.create.viewer-403", "method": "POST", "path": "/api/v1/threat-intel/iocs", "auth": "viewer",
     "json": {"indicator_type": "ip", "value": "198.51.100.9", "source": "harness"}},
    {"id": "ti.iocs.create.val-bad-ip", "method": "POST", "path": "/api/v1/threat-intel/iocs", "auth": "admin",
     "json": {"indicator_type": "ip", "value": "999.999.1.1", "source": "harness"}},
    {"id": "ti.iocs.create.val-bad-type", "method": "POST", "path": "/api/v1/threat-intel/iocs", "auth": "admin",
     "json": {"indicator_type": "meteor", "value": "x", "source": "harness"}},
    {"id": "ti.iocs.create.duplicate-409", "method": "POST", "path": "/api/v1/threat-intel/iocs", "auth": "admin",
     "json": {"indicator_type": "ip", "value": "203.0.113.7", "source": "harness"}},
    {"id": "ti.iocs.create.happy", "method": "POST", "path": "/api/v1/threat-intel/iocs", "auth": "maintainer",
     "json": {"indicator_type": "ip", "value": "198.51.100.9", "threat_level": "high",
              "confidence": 0.75, "source": "harness", "tags": ["Corpus", "TEST"]}},
    {"id": "ti.iocs.bulk.mixed", "method": "POST", "path": "/api/v1/threat-intel/iocs/bulk", "auth": "admin",
     "json": {"indicators": [
         {"indicator_type": "domain", "value": "evil.example.com", "threat_level": "critical",
          "confidence": 0.99, "source": "bulk-update"},
         {"indicator_type": "domain", "value": "new-bad.example.org", "threat_level": "medium",
          "source": "bulk-new"}]}},
    {"id": "ti.iocs.bulk.val-invalid-item", "method": "POST", "path": "/api/v1/threat-intel/iocs/bulk", "auth": "admin",
     "json": {"indicators": [{"indicator_type": "ip", "value": "not-an-ip", "source": "x"}]}},
    {"id": "ti.iocs.bulk.viewer-403", "method": "POST", "path": "/api/v1/threat-intel/iocs/bulk", "auth": "viewer",
     "json": {"indicators": []}},
    {"id": "ti.iocs.delete.maintainer-403", "method": "DELETE", "path": "/api/v1/threat-intel/iocs/6", "auth": "maintainer"},
    {"id": "ti.iocs.delete.404", "method": "DELETE", "path": "/api/v1/threat-intel/iocs/999", "auth": "admin"},
    {"id": "ti.iocs.delete.happy", "method": "DELETE", "path": "/api/v1/threat-intel/iocs/6", "auth": "admin"},
    {"id": "ti.iocs.search.value-substring", "method": "POST", "path": "/api/v1/threat-intel/iocs/search", "auth": "viewer",
     "json": {"query": "example"}},
    {"id": "ti.iocs.search.filters", "method": "POST", "path": "/api/v1/threat-intel/iocs/search", "auth": "viewer",
     "json": {"indicator_type": ["ip"], "threat_level": ["high"], "confidence_min": 0.5,
              "include_expired": True}},
    {"id": "ti.iocs.search.val-per-page", "method": "POST", "path": "/api/v1/threat-intel/iocs/search", "auth": "viewer",
     "json": {"per_page": 9999}},
    {"id": "ti.iocs.lookup.hit", "method": "POST", "path": "/api/v1/threat-intel/iocs/lookup", "auth": "viewer",
     "json": {"type": "ip", "value": "203.0.113.7"}},
    {"id": "ti.iocs.lookup.miss", "method": "POST", "path": "/api/v1/threat-intel/iocs/lookup", "auth": "viewer",
     "json": {"type": "domain", "value": "innocent.example.net"}},
    {"id": "ti.iocs.lookup.expired-miss", "method": "POST", "path": "/api/v1/threat-intel/iocs/lookup", "auth": "viewer",
     "json": {"type": "ip", "value": "192.0.2.66"}},
    {"id": "ti.iocs.lookup.missing-fields", "method": "POST", "path": "/api/v1/threat-intel/iocs/lookup", "auth": "viewer",
     "json": {"type": "ip"}},
    {"id": "ti.statistics", "method": "GET", "path": "/api/v1/threat-intel/statistics", "auth": "viewer"},
    {"id": "ti.feeds", "method": "GET", "path": "/api/v1/threat-intel/feeds", "auth": "viewer"},

    # ── approvals ────────────────────────────────────────────────────────
    {"id": "approvals.list", "method": "GET", "path": "/api/v1/approvals", "auth": "viewer"},
    {"id": "approvals.list.filters", "method": "GET", "path": "/api/v1/approvals", "auth": "viewer",
     "query": "status=pending&type=certificate"},
    {"id": "approvals.list.requester-filter", "method": "GET", "path": "/api/v1/approvals", "auth": "viewer",
     "query": "requester_id=2"},
    {"id": "approvals.list.no-token", "method": "GET", "path": "/api/v1/approvals", "auth": "none"},
    {"id": "approvals.pending.maintainer", "method": "GET", "path": "/api/v1/approvals/pending", "auth": "maintainer"},
    {"id": "approvals.pending.viewer-403", "method": "GET", "path": "/api/v1/approvals/pending", "auth": "viewer"},
    {"id": "approvals.get.full", "method": "GET", "path": "/api/v1/approvals/3", "auth": "viewer"},
    {"id": "approvals.get.404", "method": "GET", "path": "/api/v1/approvals/999", "auth": "viewer"},
    {"id": "approvals.create.happy-viewer", "method": "POST", "path": "/api/v1/approvals", "auth": "viewer",
     "json": {"request_type": "certificate", "resource_id": "res-100", "resource_type": "cert",
              "required_approvals": 2, "expires_hours": 48, "metadata": {"note": "harness"}}},
    {"id": "approvals.create.val-bad-type", "method": "POST", "path": "/api/v1/approvals", "auth": "viewer",
     "json": {"request_type": "bogus", "resource_id": "r", "resource_type": "t"}},
    {"id": "approvals.create.val-approvals-range", "method": "POST", "path": "/api/v1/approvals", "auth": "viewer",
     "json": {"request_type": "user", "resource_id": "r", "resource_type": "t",
              "required_approvals": 99}},
    {"id": "approvals.decide.admin-approve", "method": "POST", "path": "/api/v1/approvals/1/decide", "auth": "admin",
     "json": {"approved": True, "reason": "looks good"}},
    {"id": "approvals.decide.double-decide-400", "method": "POST", "path": "/api/v1/approvals/1/decide", "auth": "admin",
     "json": {"approved": True}},
    {"id": "approvals.decide.own-request-403", "method": "POST", "path": "/api/v1/approvals/1/decide", "auth": "maintainer",
     "json": {"approved": True}},
    {"id": "approvals.decide.reject", "method": "POST", "path": "/api/v1/approvals/2/decide", "auth": "maintainer",
     "json": {"approved": False, "reason": "not needed"}},
    {"id": "approvals.decide.already-completed-400", "method": "POST", "path": "/api/v1/approvals/2/decide", "auth": "admin",
     "json": {"approved": True}},
    {"id": "approvals.decide.expired-400", "method": "POST", "path": "/api/v1/approvals/4/decide", "auth": "admin",
     "json": {"approved": True}},
    {"id": "approvals.decide.viewer-403", "method": "POST", "path": "/api/v1/approvals/1/decide", "auth": "viewer",
     "json": {"approved": True}},
    {"id": "approvals.decide.404", "method": "POST", "path": "/api/v1/approvals/999/decide", "auth": "admin",
     "json": {"approved": True}},
    {"id": "approvals.decide.val-missing-approved", "method": "POST", "path": "/api/v1/approvals/1/decide", "auth": "admin",
     "json": {"reason": "no decision"}},
    {"id": "approvals.cancel.not-requester-403", "method": "POST", "path": "/api/v1/approvals/1/cancel", "auth": "viewer"},
    {"id": "approvals.cancel.requester", "method": "POST", "path": "/api/v1/approvals/1/cancel", "auth": "maintainer"},
    {"id": "approvals.cancel.completed-400", "method": "POST", "path": "/api/v1/approvals/3/cancel", "auth": "admin"},
    {"id": "approvals.cancel.404", "method": "POST", "path": "/api/v1/approvals/999/cancel", "auth": "admin"},
    {"id": "approvals.statistics.maintainer", "method": "GET", "path": "/api/v1/approvals/statistics", "auth": "maintainer"},
    {"id": "approvals.statistics.viewer-403", "method": "GET", "path": "/api/v1/approvals/statistics", "auth": "viewer"},

    # ── edr (agent HMAC endpoints) ───────────────────────────────────────
    # enrollment_token: v2 requires it to resolve a *new* agent's tenant
    # (routes/endpoint.rs::resolve_enrollment_token, migration 0005); v1 has
    # no such concept and silently ignores the unknown field (pydantic v2
    # default extra="ignore" on EDRAgentRegisterRequest). Raw value must
    # match the seeded hash in seed_v2.sql's endpoint_enrollment_tokens row.
    {"id": "edr.register.new-agent", "method": "POST", "path": "/api/v1/edr/register", "auth": "agent:agent-delta",
     "json": {"agent_id": "agent-delta", "hostname": "db-04.corp", "ip_address": "10.0.0.14",
              "os_type": "linux", "os_version": "Debian 12", "agent_version": "1.4.2",
              "metadata": {"site": "dal2"}, "enrollment_token": "parity-fixed-enrollment-token-0001"}},
    {"id": "edr.register.re-register", "sleep_before": 1.1, "method": "POST", "path": "/api/v1/edr/register", "auth": "agent:agent-alpha",
     "json": {"agent_id": "agent-alpha", "hostname": "web-01.corp", "ip_address": "10.0.0.11",
              "os_type": "linux", "os_version": "Ubuntu 24.04", "agent_version": "1.5.0",
              "metadata": {"site": "dal2"}}},
    {"id": "edr.register.bad-key-401", "method": "POST", "path": "/api/v1/edr/register", "auth": "agentbad:agent-alpha",
     "json": {"agent_id": "agent-alpha", "hostname": "h", "agent_version": "1.0.0"}},
    {"id": "edr.register.missing-headers-401", "method": "POST", "path": "/api/v1/edr/register", "auth": "agentmissing",
     "json": {"agent_id": "agent-alpha", "hostname": "h", "agent_version": "1.0.0"}},
    {"id": "edr.register.val-missing-fields", "method": "POST", "path": "/api/v1/edr/register", "auth": "agent:agent-delta",
     "json": {"agent_id": "agent-delta"}},
    {"id": "edr.heartbeat.happy", "sleep_before": 1.1, "method": "POST", "path": "/api/v1/edr/heartbeat", "auth": "agent:agent-alpha",
     "json": {"agent_id": "agent-alpha", "status": "active", "metadata": {"load": "0.5"}}},
    {"id": "edr.heartbeat.unregistered-404", "method": "POST", "path": "/api/v1/edr/heartbeat", "auth": "agent:agent-zeta",
     "json": {"agent_id": "agent-zeta"}},
    {"id": "edr.heartbeat.val-bad-status", "method": "POST", "path": "/api/v1/edr/heartbeat", "auth": "agent:agent-alpha",
     "json": {"agent_id": "agent-alpha", "status": "hibernating"}},
    {"id": "edr.events.single", "method": "POST", "path": "/api/v1/edr/events", "auth": "agent:agent-alpha",
     "json": {"agent_id": "agent-alpha", "event_type": "process_start", "severity": "low",
              "process_name": "ls", "command_line": "ls -la", "details": {"cwd": "/tmp"}}},
    {"id": "edr.events.batch-mixed", "sleep_before": 1.1, "method": "POST", "path": "/api/v1/edr/events", "auth": "agent:agent-alpha",
     "json": [
         {"agent_id": "agent-alpha", "event_type": "network_connection", "severity": "high",
          "process_name": "nc", "network_connections": [{"dst": "203.0.113.9", "port": 4444}]},
         {"agent_id": "agent-unknown", "event_type": "process_start"},
         {"agent_id": "agent-alpha", "severity": "low"}]},
    {"id": "edr.config.get", "method": "GET", "path": "/api/v1/edr/config", "auth": "agent:agent-alpha"},
    {"id": "edr.config.metadata-override", "method": "GET", "path": "/api/v1/edr/config", "auth": "agent:agent-beta"},
    {"id": "edr.config.unregistered-404", "method": "GET", "path": "/api/v1/edr/config", "auth": "agent:agent-zeta"},

    # ── edr (operator JWT endpoints) ─────────────────────────────────────
    {"id": "edr.agents.list.maintainer", "method": "GET", "path": "/api/v1/edr/agents", "auth": "maintainer"},
    {"id": "edr.agents.list.viewer-403", "method": "GET", "path": "/api/v1/edr/agents", "auth": "viewer"},
    {"id": "edr.agents.list.filter-status", "method": "GET", "path": "/api/v1/edr/agents", "auth": "admin",
     "query": "status=inactive"},
    {"id": "edr.agents.list.filter-os", "method": "GET", "path": "/api/v1/edr/agents", "auth": "admin",
     "query": "os_type=linux"},
    {"id": "edr.agents.get", "method": "GET", "path": "/api/v1/edr/agents/agent-beta", "auth": "viewer"},
    {"id": "edr.agents.get-404", "method": "GET", "path": "/api/v1/edr/agents/agent-nope", "auth": "viewer"},
    {"id": "edr.agents.events", "method": "GET", "path": "/api/v1/edr/agents/agent-alpha/events", "auth": "viewer"},
    {"id": "edr.agents.events-paginated", "method": "GET", "path": "/api/v1/edr/agents/agent-alpha/events",
     "auth": "viewer", "query": "page=2&per_page=2"},
    {"id": "edr.agents.events-404", "method": "GET", "path": "/api/v1/edr/agents/agent-nope/events", "auth": "viewer"},
    {"id": "edr.deactivate.maintainer-403", "method": "POST", "path": "/api/v1/edr/agents/agent-beta/deactivate",
     "auth": "maintainer"},
    {"id": "edr.deactivate.admin", "method": "POST", "path": "/api/v1/edr/agents/agent-beta/deactivate",
     "auth": "admin"},
    {"id": "edr.deactivate.404", "method": "POST", "path": "/api/v1/edr/agents/agent-nope/deactivate",
     "auth": "admin"},
    {"id": "edr.agents.get-after-deactivate", "method": "GET", "path": "/api/v1/edr/agents/agent-beta",
     "auth": "viewer"},
    {"id": "edr.statistics", "method": "GET", "path": "/api/v1/edr/statistics", "auth": "viewer"},

    # ── s3-scan ──────────────────────────────────────────────────────────
    {"id": "s3.buckets.list", "method": "GET", "path": "/api/v1/s3-scan/buckets", "auth": "viewer"},
    {"id": "s3.buckets.list.no-token", "method": "GET", "path": "/api/v1/s3-scan/buckets", "auth": "none"},
    {"id": "s3.buckets.get", "method": "GET", "path": "/api/v1/s3-scan/buckets/1", "auth": "viewer"},
    {"id": "s3.buckets.get-404", "method": "GET", "path": "/api/v1/s3-scan/buckets/999", "auth": "viewer"},
    {"id": "s3.buckets.create.viewer-403", "method": "POST", "path": "/api/v1/s3-scan/buckets", "auth": "viewer",
     "json": {"name": "n", "endpoint_url": "http://parity-stub:9999", "bucket_name": "b",
              "access_key_id": "k", "secret_access_key": "s"}},
    {"id": "s3.buckets.create.val-bad-endpoint", "method": "POST", "path": "/api/v1/s3-scan/buckets", "auth": "admin",
     "json": {"name": "bad", "endpoint_url": "ftp://nope", "bucket_name": "b",
              "access_key_id": "k", "secret_access_key": "s"}},
    {"id": "s3.buckets.create.duplicate-409", "method": "POST", "path": "/api/v1/s3-scan/buckets", "auth": "admin",
     "json": {"name": "dup-of-prod", "endpoint_url": "http://parity-stub:9999", "bucket_name": "artifacts",
              "access_key_id": "AKIAX", "secret_access_key": "secretsecret"}},
    {"id": "s3.buckets.create.happy", "method": "POST", "path": "/api/v1/s3-scan/buckets", "auth": "maintainer",
     "json": {"name": "quarantine", "endpoint_url": "http://parity-stub:9999", "bucket_name": "quarantine",
              "access_key_id": "AKIAQUARANTINE001", "secret_access_key": "quarantinesecret9999",
              "file_types_filter": ["exe", ".DLL"], "max_file_size_mb": 50}},
    {"id": "s3.buckets.update.happy", "method": "PUT", "path": "/api/v1/s3-scan/buckets/4", "auth": "maintainer",
     "json": {"max_file_size_mb": 75, "yara_enabled": True}},
    {"id": "s3.buckets.update.404", "method": "PUT", "path": "/api/v1/s3-scan/buckets/999", "auth": "admin",
     "json": {"name": "ghost"}},
    {"id": "s3.buckets.update.val-bad-size", "method": "PUT", "path": "/api/v1/s3-scan/buckets/1", "auth": "admin",
     "json": {"max_file_size_mb": 9000}},
    {"id": "s3.buckets.get-after-update", "method": "GET", "path": "/api/v1/s3-scan/buckets/4", "auth": "viewer"},
    {"id": "s3.buckets.delete.maintainer-403", "method": "DELETE", "path": "/api/v1/s3-scan/buckets/1",
     "auth": "maintainer"},
    {"id": "s3.buckets.delete.404", "method": "DELETE", "path": "/api/v1/s3-scan/buckets/999", "auth": "admin"},
    {"id": "s3.buckets.delete.v2-only-defect11", "method": "DELETE", "path": "/api/v1/s3-scan/buckets/4",
     "auth": "admin"},
    {"id": "s3.buckets.test.happy", "method": "POST", "path": "/api/v1/s3-scan/buckets/1/test", "auth": "admin"},
    {"id": "s3.buckets.test.viewer-403", "method": "POST", "path": "/api/v1/s3-scan/buckets/1/test", "auth": "viewer"},
    {"id": "s3.buckets.test.404", "method": "POST", "path": "/api/v1/s3-scan/buckets/999/test", "auth": "admin"},
    {"id": "s3.scan.trigger-disabled-400", "method": "POST", "path": "/api/v1/s3-scan/buckets/2/scan", "auth": "admin",
     "json": {}},
    {"id": "s3.scan.trigger-404", "method": "POST", "path": "/api/v1/s3-scan/buckets/999/scan", "auth": "admin",
     "json": {}},
    {"id": "s3.scan.trigger-viewer-403", "method": "POST", "path": "/api/v1/s3-scan/buckets/1/scan", "auth": "viewer",
     "json": {}},
    # defect #1/#4: v1 inserts unknown columns + job_type "manual" → broken
    {"id": "s3.scan.trigger-happy-defect1", "method": "POST", "path": "/api/v1/s3-scan/buckets/1/scan", "auth": "admin",
     "json": {"prefix_filter": "incoming/", "force_rescan": True}},
    {"id": "s3.jobs.list-defect1", "method": "GET", "path": "/api/v1/s3-scan/jobs", "auth": "viewer"},
    {"id": "s3.jobs.list.filter-empty", "method": "GET", "path": "/api/v1/s3-scan/jobs", "auth": "viewer",
     "query": "status=failed"},
    {"id": "s3.jobs.get-defect1", "method": "GET", "path": "/api/v1/s3-scan/jobs/1", "auth": "viewer"},
    {"id": "s3.jobs.get-404", "method": "GET", "path": "/api/v1/s3-scan/jobs/999", "auth": "viewer"},
    {"id": "s3.jobs.cancel.running", "method": "POST", "path": "/api/v1/s3-scan/jobs/2/cancel", "auth": "maintainer"},
    {"id": "s3.jobs.cancel.already-cancelled-400", "method": "POST", "path": "/api/v1/s3-scan/jobs/3/cancel",
     "auth": "admin"},
    {"id": "s3.jobs.cancel.viewer-403", "method": "POST", "path": "/api/v1/s3-scan/jobs/1/cancel", "auth": "viewer"},
    {"id": "s3.jobs.cancel.404", "method": "POST", "path": "/api/v1/s3-scan/jobs/999/cancel", "auth": "admin"},
    {"id": "s3.results.list-defect1", "method": "GET", "path": "/api/v1/s3-scan/results", "auth": "viewer"},
    {"id": "s3.results.list.filter-empty", "method": "GET", "path": "/api/v1/s3-scan/results", "auth": "viewer",
     "query": "scan_status=skipped"},
    {"id": "s3.results.list.filter-malware-defect1", "method": "GET", "path": "/api/v1/s3-scan/results",
     "auth": "viewer", "query": "is_malware=true"},
    {"id": "s3.results.get-defect1", "method": "GET", "path": "/api/v1/s3-scan/results/2", "auth": "viewer"},
    {"id": "s3.results.get-404", "method": "GET", "path": "/api/v1/s3-scan/results/999", "auth": "viewer"},
    {"id": "s3.statistics-defect1", "method": "GET", "path": "/api/v1/s3-scan/statistics", "auth": "viewer"},
    {"id": "s3.schedule.get-defect1", "method": "GET", "path": "/api/v1/s3-scan/buckets/1/schedule", "auth": "viewer"},
    {"id": "s3.schedule.get-none-404", "method": "GET", "path": "/api/v1/s3-scan/buckets/2/schedule", "auth": "viewer"},
    {"id": "s3.schedule.get-bucket-404", "method": "GET", "path": "/api/v1/s3-scan/buckets/999/schedule",
     "auth": "viewer"},
    {"id": "s3.schedule.put.happy", "method": "PUT", "path": "/api/v1/s3-scan/buckets/2/schedule", "auth": "maintainer",
     "json": {"cron_expression": "30 1 * * 0", "timezone": "UTC", "enabled": True}},
    {"id": "s3.schedule.put.update-existing", "method": "PUT", "path": "/api/v1/s3-scan/buckets/1/schedule",
     "auth": "admin", "json": {"cron_expression": "15 4 * * *", "timezone": "UTC", "enabled": False}},
    {"id": "s3.schedule.put.val-bad-cron", "method": "PUT", "path": "/api/v1/s3-scan/buckets/2/schedule",
     "auth": "admin", "json": {"cron_expression": "every day at noon"}},
    {"id": "s3.schedule.put.viewer-403", "method": "PUT", "path": "/api/v1/s3-scan/buckets/2/schedule",
     "auth": "viewer", "json": {"cron_expression": "0 3 * * *"}},
    {"id": "s3.schedule.delete.happy", "method": "DELETE", "path": "/api/v1/s3-scan/buckets/2/schedule",
     "auth": "admin"},
    {"id": "s3.schedule.delete.none-404", "method": "DELETE", "path": "/api/v1/s3-scan/buckets/2/schedule",
     "auth": "admin"},
    {"id": "s3.upload.post-defect1", "method": "POST", "path": "/api/v1/s3-scan/upload", "auth": "viewer",
     "files": {"file": ["harness-sample.bin", "parity harness sample content"]}},
    {"id": "s3.upload.post-no-file-400", "method": "POST", "path": "/api/v1/s3-scan/upload", "auth": "viewer",
     "files": {}},
    {"id": "s3.upload.get-defect1", "method": "GET", "path": "/api/v1/s3-scan/upload/1", "auth": "admin"},
    {"id": "s3.upload.get-not-owner-defect1", "method": "GET", "path": "/api/v1/s3-scan/upload/1", "auth": "viewer"},
    {"id": "s3.upload.history-defect1", "method": "GET", "path": "/api/v1/s3-scan/upload/history", "auth": "viewer"},
    {"id": "s3.upload.delete-defect1", "method": "DELETE", "path": "/api/v1/s3-scan/upload/2", "auth": "viewer"},
    {"id": "s3.ti.create-indicator.404", "method": "POST", "path": "/api/v1/s3-scan/results/999/create-indicator",
     "auth": "admin"},
    {"id": "s3.ti.create-indicator.not-threat-400", "method": "POST",
     "path": "/api/v1/s3-scan/results/1/create-indicator", "auth": "admin"},
    {"id": "s3.ti.create-indicator.viewer-403", "method": "POST",
     "path": "/api/v1/s3-scan/results/2/create-indicator", "auth": "viewer"},
    {"id": "s3.ti.create-indicator.threat-defect1", "method": "POST",
     "path": "/api/v1/s3-scan/results/2/create-indicator", "auth": "admin"},
    {"id": "s3.ti.enrichment-defect1", "method": "GET", "path": "/api/v1/s3-scan/results/2/ti-enrichment",
     "auth": "viewer"},
    {"id": "s3.ti.enrichment-404", "method": "GET", "path": "/api/v1/s3-scan/results/999/ti-enrichment",
     "auth": "viewer"},
    {"id": "s3.hash-lookup.hit-defect3", "method": "POST", "path": "/api/v1/s3-scan/hash-lookup", "auth": "viewer",
     "json": {"hash_value": "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3b5d4e9c7a3f1e2d4c5b6a798"}},
    {"id": "s3.hash-lookup.miss", "method": "POST", "path": "/api/v1/s3-scan/hash-lookup", "auth": "viewer",
     "json": {"hash_value": "c0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ffeec0ffee0000"}},
    {"id": "s3.hash-lookup.val-bad-hex", "method": "POST", "path": "/api/v1/s3-scan/hash-lookup", "auth": "viewer",
     "json": {"hash_value": "zzzz8fe5ccb19ba61c4c0873d391e987"}},

    # ── siem ─────────────────────────────────────────────────────────────
    {"id": "siem.health", "method": "GET", "path": "/api/v1/siem/health", "auth": "none"},
    {"id": "siem.ingest.proxy", "method": "POST", "path": "/api/v1/siem/ingest", "auth": "viewer",
     "json": {"events": [{"class_name": "auth", "severity_id": 3, "message": "harness event"}]}},
    {"id": "siem.ingest.no-token", "method": "POST", "path": "/api/v1/siem/ingest", "auth": "none",
     "json": {}},
    {"id": "siem.search.opensearch-down", "method": "GET", "path": "/api/v1/siem/search", "auth": "viewer",
     "query": "q=harness"},
    {"id": "siem.stats.opensearch-down", "method": "GET", "path": "/api/v1/siem/stats", "auth": "viewer"},
    {"id": "siem.config.get", "method": "GET", "path": "/api/v1/siem/config", "auth": "viewer"},
    {"id": "siem.config.put.happy", "method": "PUT", "path": "/api/v1/siem/config", "auth": "admin",
     "json": {"retention_days": 30}},
    {"id": "siem.config.put.no-body-field", "method": "PUT", "path": "/api/v1/siem/config", "auth": "admin",
     "json": {}},
    {"id": "siem.config.put.out-of-range", "method": "PUT", "path": "/api/v1/siem/config", "auth": "admin",
     "json": {"retention_days": 500}},
    {"id": "siem.config.put.wrong-type", "method": "PUT", "path": "/api/v1/siem/config", "auth": "admin",
     "json": {"retention_days": "abc"}},
    {"id": "siem.config.put.viewer-403", "method": "PUT", "path": "/api/v1/siem/config", "auth": "viewer",
     "json": {"retention_days": 10}},

    # ── asm (pure proxy → stub) ──────────────────────────────────────────
    {"id": "asm.scans.create", "method": "POST", "path": "/api/v1/asm/scans", "auth": "admin",
     "json": {"target": "192.0.2.0/28", "profile": "quick"}},
    {"id": "asm.scans.create-empty-body", "method": "POST", "path": "/api/v1/asm/scans", "auth": "admin"},
    {"id": "asm.scans.list", "method": "GET", "path": "/api/v1/asm/scans", "auth": "viewer",
     "query": "page=2&status=done"},
    {"id": "asm.scans.get", "method": "GET", "path": "/api/v1/asm/scans/7", "auth": "viewer"},
    {"id": "asm.scans.hosts", "method": "GET", "path": "/api/v1/asm/scans/7/hosts", "auth": "viewer"},
    {"id": "asm.scans.screenshots", "method": "GET", "path": "/api/v1/asm/scans/7/screenshots", "auth": "viewer"},
    {"id": "asm.scans.certs", "method": "GET", "path": "/api/v1/asm/scans/7/certs", "auth": "viewer"},
    {"id": "asm.scans.diff", "method": "GET", "path": "/api/v1/asm/scans/7/diff", "auth": "viewer"},
    {"id": "asm.scans.report", "method": "GET", "path": "/api/v1/asm/scans/7/report", "auth": "viewer"},
    {"id": "asm.settings.ports.get", "method": "GET", "path": "/api/v1/asm/settings/ports", "auth": "viewer"},
    {"id": "asm.settings.ports.put.admin", "method": "PUT", "path": "/api/v1/asm/settings/ports", "auth": "admin",
     "json": {"top_ports": 1000}},
    {"id": "asm.settings.ports.put.viewer-403", "method": "PUT", "path": "/api/v1/asm/settings/ports",
     "auth": "viewer", "json": {"top_ports": 10}},
    {"id": "asm.scans.no-token", "method": "GET", "path": "/api/v1/asm/scans", "auth": "none"},

    # ── darwin (proxy → stub, license-gated; dev/bypass opens both sides) ─
    {"id": "darwin.status", "method": "GET", "path": "/api/v1/darwin/status", "auth": "viewer"},
    {"id": "darwin.status.no-token", "method": "GET", "path": "/api/v1/darwin/status", "auth": "none"},
    {"id": "darwin.repos.list", "method": "GET", "path": "/api/v1/darwin/repos", "auth": "viewer",
     "query": "page=1"},
    {"id": "darwin.repos.create.admin", "method": "POST", "path": "/api/v1/darwin/repos", "auth": "admin",
     "json": {"url": "https://github.com/example/repo", "branch": "main"}},
    {"id": "darwin.repos.create.viewer-403", "method": "POST", "path": "/api/v1/darwin/repos", "auth": "viewer",
     "json": {"url": "https://github.com/example/repo"}},
    {"id": "darwin.repos.create.maintainer-403", "method": "POST", "path": "/api/v1/darwin/repos",
     "auth": "maintainer", "json": {"url": "https://github.com/example/repo"}},
    {"id": "darwin.repos.get", "method": "GET", "path": "/api/v1/darwin/repos/3", "auth": "viewer"},
    {"id": "darwin.repos.update.admin", "method": "PUT", "path": "/api/v1/darwin/repos/3", "auth": "admin",
     "json": {"branch": "develop"}},
    {"id": "darwin.repos.delete.admin", "method": "DELETE", "path": "/api/v1/darwin/repos/3", "auth": "admin"},
    {"id": "darwin.repos.delete.maintainer-403", "method": "DELETE", "path": "/api/v1/darwin/repos/3",
     "auth": "maintainer"},
    {"id": "darwin.reviews.list", "method": "GET", "path": "/api/v1/darwin/reviews", "auth": "viewer"},
    # v1 quirk: role_required("maintainer") — admins are NOT allowed
    {"id": "darwin.reviews.create.maintainer", "method": "POST", "path": "/api/v1/darwin/reviews",
     "auth": "maintainer", "json": {"repo_id": 3, "pr_number": 42}},
    {"id": "darwin.reviews.create.admin-403", "method": "POST", "path": "/api/v1/darwin/reviews", "auth": "admin",
     "json": {"repo_id": 3, "pr_number": 42}},
    {"id": "darwin.reviews.get", "method": "GET", "path": "/api/v1/darwin/reviews/9", "auth": "viewer"},
    {"id": "darwin.plans.list", "method": "GET", "path": "/api/v1/darwin/plans", "auth": "viewer"},
    {"id": "darwin.plans.create", "method": "POST", "path": "/api/v1/darwin/plans", "auth": "viewer",
     "json": {"issue_url": "https://github.com/example/repo/issues/1"}},
    {"id": "darwin.plans.get", "method": "GET", "path": "/api/v1/darwin/plans/2", "auth": "viewer"},

    # ── research (v1 runtime-broken → decision #2: v2 implements properly) ─
    {"id": "research.lookup.no-token", "method": "POST", "path": "/api/v1/research/lookup", "auth": "none",
     "json": {"query": "example.com"}},
    {"id": "research.lookup.val-missing-query", "method": "POST", "path": "/api/v1/research/lookup", "auth": "viewer",
     "json": {}},
    {"id": "research.lookup.decision2", "method": "POST", "path": "/api/v1/research/lookup", "auth": "viewer",
     "json": {"query": "198.51.100.7", "include_whois": False, "include_dns": False, "include_asn": False}},
    {"id": "research.whois.val-missing-type", "method": "POST", "path": "/api/v1/research/whois", "auth": "viewer",
     "json": {"query": "example.com"}},
    {"id": "research.whois.decision2", "method": "POST", "path": "/api/v1/research/whois", "auth": "viewer",
     "json": {"query": "example.com", "indicator_type": "domain"}},
    {"id": "research.dns.decision2", "method": "POST", "path": "/api/v1/research/dns", "auth": "viewer",
     "json": {"query": "localhost.localdomain"}},
    {"id": "research.asn.decision2", "method": "POST", "path": "/api/v1/research/asn", "auth": "viewer",
     "json": {"query": "198.51.100.7", "indicator_type": "ip"}},
    {"id": "research.shodan.disabled", "method": "POST", "path": "/api/v1/research/shodan", "auth": "viewer",
     "json": {"query": "198.51.100.7"}},
    {"id": "research.maltego.disabled", "method": "POST", "path": "/api/v1/research/maltego", "auth": "viewer",
     "json": {"query": "example.com"}},
    {"id": "research.config.decision2", "method": "GET", "path": "/api/v1/research/config", "auth": "viewer"},

    # ── case-sensitivity tail (may create per-side drift until v2 fixed) ──
    {"id": "auth.login.mixed-case-email", "sleep_before": 1.1, "method": "POST", "path": "/api/v1/auth/login", "auth": "none",
     "json": {"email": "ADMIN@skauswatch.dev", "password": SEED_PASSWORD}},
    {"id": "auth.register.mixed-case-email", "method": "POST", "path": "/api/v1/auth/register", "auth": "none",
     "json": {"email": "MiXeD@skauswatch.dev", "password": "Password123!", "full_name": "Mixed Case"}},
]
