apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icebox-sync-worker.fullname" . }}-secrets
  labels:
    {{- include "icebox-sync-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASS: {{ .Values.secrets.DB_PASS | quote }}
  REDIS_PASS: {{ .Values.secrets.REDIS_PASS | quote }}
  ICEBOX_MEK: {{ .Values.secrets.ICEBOX_MEK | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | quote }}
  AWS_REGION: {{ .Values.secrets.AWS_REGION | quote }}
  AZURE_TENANT_ID: {{ .Values.secrets.AZURE_TENANT_ID | quote }}
  AZURE_CLIENT_ID: {{ .Values.secrets.AZURE_CLIENT_ID | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.secrets.AZURE_CLIENT_SECRET | quote }}
  GCP_SERVICE_ACCOUNT_JSON: {{ .Values.secrets.GCP_SERVICE_ACCOUNT_JSON | quote }}
  OCI_CONFIG: {{ .Values.secrets.OCI_CONFIG | quote }}
  K8S_KUBECONFIG: {{ .Values.secrets.K8S_KUBECONFIG | quote }}
