apiVersion: v1
kind: Secret
metadata:
  name: icebox-flask-backend-secrets
  namespace: icebox
type: Opaque
stringData:
  DB_USER: "icebox-app"
  DB_PASS: "changeme"
  REDIS_PASS: ""
  ICEBOX_MEK: "changeme-32-chars-minimum-length!"
  JWT_SECRET: "changeme-jwt-secret"
  LICENSE_KEY: ""
