apiVersion: v2
name: skauswatch-edr-agent
description: SkausWatch EDR Agent (Go, DaemonSet)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - skauswatch
  - edr
  - agent
  - go
  - daemonset
maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io
