apiVersion: v2
name: skauswatch-pki
description: SkausWatch PKI Server Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - skauswatch
  - pki
  - flask
  - python
maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io
