{{- if .Values.spire.enabled }}
{{- if .Values.spire.agent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skauswatch-spire.agentServiceAccountName" . }}
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: agent
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
