{{- if .Values.spire.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "skauswatch-spire.fullname" . }}-agent
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "skauswatch-spire.fullname" . }}-agent
subjects:
  - kind: ServiceAccount
    name: {{ include "skauswatch-spire.agentServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
