{{- if and .Values.spire.enabled .Values.spire.autoEnroll.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "skauswatch-spire.fullname" . }}-auto-enroll
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: auto-enroll
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
{{- end }}
