{{- if and .Values.spire.enabled .Values.spire.autoEnroll.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skauswatch-spire.fullname" . }}-auto-enroll
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: auto-enroll
  namespace: {{ .Release.Namespace }}
{{- end }}
