{{- if and .Values.spire.enabled .Values.spire.csiDriver.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skauswatch-spire.csiDriverServiceAccountName" . }}
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: csi-driver
  namespace: {{ .Release.Namespace }}
{{- end }}
