{{- if and .Values.spire.enabled .Values.spire.oidcProvider.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skauswatch-spire.fullname" . }}-oidc-provider
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: oidc-provider
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "skauswatch-spire.selectorLabels" . | nindent 4 }}
    component: oidc-provider
  ports:
  - port: {{ .Values.spire.oidcProvider.port }}
    targetPort: http
    protocol: TCP
    name: http
{{- end }}
