{{- if .Values.spire.enabled }}
{{- if gt (int .Values.spire.server.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "skauswatch-spire.fullname" . }}-server
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: server
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "skauswatch-spire.selectorLabels" . | nindent 6 }}
      component: server
{{- end }}
{{- end }}
