{{- if .Values.spire.enabled }}
{{- if .Values.spire.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skauswatch-spire.serverServiceAccountName" . }}
  labels:
    {{- include "skauswatch-spire.labels" . | nindent 4 }}
    component: server
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
