apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icebox-ssh-ca.fullname" . }}
  labels:
    {{- include "icebox-ssh-ca.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "icebox-ssh-ca.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "icebox-ssh-ca.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: ssh-ca
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: DB_TYPE
              value: {{ .Values.env.DB_TYPE | quote }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: DB_POOL_SIZE
              value: {{ .Values.env.DB_POOL_SIZE | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "icebox-ssh-ca.fullname" . }}-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "icebox-ssh-ca.fullname" . }}-secrets
                  key: DB_PASS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
