apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icebox-ssh-ca.fullname" . }}-secrets
  labels:
    {{- include "icebox-ssh-ca.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASS: {{ .Values.secrets.DB_PASS | quote }}
