replicaCount: 3

image:
  repository: registry-dal2.penguintech.cloud/skauswatch/icebox-flask-backend
  pullPolicy: Always

ingress:
  enabled: true
  host: icebox.skauswatch.app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: icebox-flask-tls-prod
      hosts:
        - icebox.skauswatch.app

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  DB_POOL_SIZE: "20"
  LOG_LEVEL: "warn"
  RELEASE_MODE: "true"
