apiVersion: v2
name: skauswatch-aaa-monitor
description: SkausWatch AAA Monitor Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - skauswatch
  - aaa
  - monitor
  - flask
  - python
maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io
