---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: skauswatch
  labels:
    app.kubernetes.io/name: monitor
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: monitor
  ports:
  - name: http
    port: 5003
    targetPort: 5003
    protocol: TCP
