---
# Beta ingress - skauswatch.penguintech.cloud
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skauswatch-webui
  namespace: skauswatch
  labels:
    app.kubernetes.io/name: webui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kustomize
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: skauswatch.penguintech.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skauswatch-webui
                port:
                  name: http
