{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skauswatch-codescan-backend.secretName" . }}
  labels:
    {{- include "skauswatch-codescan-backend.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
