apiVersion: v1
kind: Secret
metadata:
  name: checkpoint-ldap-agent-secrets
  labels:
    {{- include "checkpoint-ldap-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AGENT_TOKEN: {{ .Values.secrets.AGENT_TOKEN | b64enc | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.secrets.LDAP_BIND_PASSWORD | b64enc | quote }}
