apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkpoint-ldap-agent.fullname" . }}
  labels:
    {{- include "checkpoint-ldap-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ldap
      port: {{ .Values.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "checkpoint-ldap-agent.selectorLabels" . | nindent 4 }}
