apiVersion: v2
name: skauswatch-manager
description: SkausWatch Manager Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - skauswatch
  - manager
  - rust
  - grpc
  - api
maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io
