# Tetragon exec-allowlist for {{ include "skauswatch-scanner.fullname" . }}.
# ENFORCE: any sys_execve NOT matching one of the listed binaries is
# SIGKILLed -- blocks a dropped shell/reverse-shell/living-off-the-land
# binary (bash, sh, curl, nc, wget, python3, perl, ...) in a pod whose only
# legitimate process is the binaries below. Requires the Tetragon agent
# DaemonSet running in the cluster (cluster add-on, not part of this chart
# -- see k8s/helm/README.md "Tetragon prerequisite").
# masscan is the ASM port-discovery subprocess (services/scanner/src/
# asm.rs) -- requires CAP_NET_RAW, see the NET CAPABILITY EXCEPTION in
# values.yaml. Scan-target egress (the raw SYN/TCP traffic masscan itself
# sends) is operator-configured and NOT restricted by the CiliumNetworkPolicy
# egress list above -- that traffic is the tool's function, not a service
# dependency call, and cannot be known ahead of time. Only this pod's own
# control-plane egress (Valkey, license server) is policy-scoped.
{{- if .Values.tetragon.enabled | default true }}
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: {{ include "skauswatch-scanner.fullname" . }}-exec-allowlist
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "skauswatch-scanner.selectorLabels" . | nindent 6 }}
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
        - index: 1
          type: "string_arr"
      selectors:
        - matchArgs:
            - index: 0
              operator: "NotEqual"
              values:
                - "/usr/local/bin/skauswatch-scanner"
                - "/usr/bin/masscan"
          matchActions:
            - action: Sigkill
{{- end }}
