// Code generated by protoc-gen-go-grpc — DO NOT EDIT manually.
// Source: ../../checkpoint-core/proto/checkpoint.proto
// To regenerate (Go):
//
//	protoc --go_out=. --go-grpc_out=. proto/checkpoint.proto
//
// To regenerate (Python, for checkpoint-core):
//
//	cd checkpoint-core && python -m grpc_tools.protoc --python_out=. --grpc_python_out=. proto/checkpoint.proto
package checkpointpb

import (
	"context"

	"google.golang.org/grpc"
)

// ─── Message Types ────────────────────────────────────────────────────────────

// LdapBindRequest is sent by the agent when a client binds.
type LdapBindRequest struct {
	Dn       string `json:"dn"`
	Password string `json:"password"`
	AgentId  string `json:"agent_id"`
	ClientIp string `json:"client_ip"`
}

// LdapBindResponse is returned by checkpoint-core for a bind operation.
type LdapBindResponse struct {
	Success  bool   `json:"success"`
	UserUuid string `json:"user_uuid"`
	Error    string `json:"error,omitempty"`
}

// LdapSearchRequest is sent when an LDAP client searches.
type LdapSearchRequest struct {
	BaseDn     string   `json:"base_dn"`
	Filter     string   `json:"filter"`
	Attributes []string `json:"attributes"`
	Scope      int32    `json:"scope"`
	SizeLimit  int32    `json:"size_limit"`
	AgentId    string   `json:"agent_id"`
}

// LdapAttribute is a single multi-valued LDAP attribute.
type LdapAttribute struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

// LdapEntry is a single LDAP directory entry.
type LdapEntry struct {
	Dn         string          `json:"dn"`
	Attributes []*LdapAttribute `json:"attributes"`
}

// LdapSearchResponse contains the entries returned by a search.
type LdapSearchResponse struct {
	Entries   []*LdapEntry `json:"entries"`
	ResultCode int32       `json:"result_code"`
	Error     string       `json:"error,omitempty"`
}

// LdapCompareRequest checks whether a DN has a given attribute=value.
type LdapCompareRequest struct {
	Dn        string `json:"dn"`
	Attribute string `json:"attribute"`
	Value     string `json:"value"`
	AgentId   string `json:"agent_id"`
}

// LdapCompareResponse is the result of a compare operation.
type LdapCompareResponse struct {
	Matched bool   `json:"matched"`
	Error   string `json:"error,omitempty"`
}

// LdapModification describes a single LDAP modify operation.
type LdapModification struct {
	Operation int32    `json:"operation"` // 0=add, 1=delete, 2=replace
	Attribute string   `json:"attribute"`
	Values    []string `json:"values"`
}

// LdapModifyRequest modifies attributes on a DN.
type LdapModifyRequest struct {
	Dn            string              `json:"dn"`
	Modifications []*LdapModification `json:"modifications"`
	AgentId       string              `json:"agent_id"`
}

// LdapModifyResponse is the result of a modify operation.
type LdapModifyResponse struct {
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

// VerifyTokenRequest checks a JIT or API token against checkpoint-core.
type VerifyTokenRequest struct {
	Token   string `json:"token"`
	AgentId string `json:"agent_id"`
}

// VerifyTokenResponse is returned by checkpoint-core for a token verification.
type VerifyTokenResponse struct {
	Valid     bool   `json:"valid"`
	UserUuid  string `json:"user_uuid"`
	Scope     string `json:"scope"`
	ExpiresAt int64  `json:"expires_at"`
	Error     string `json:"error,omitempty"`
}

// RegisterAgentRequest is sent on agent startup to announce this instance.
type RegisterAgentRequest struct {
	AgentId  string `json:"agent_id"`
	Hostname string `json:"hostname"`
	Version  string `json:"version"`
	SiteName string `json:"site_name"`
}

// RegisterAgentResponse is returned after agent registration.
type RegisterAgentResponse struct {
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

// HeartbeatRequest is sent every 30 seconds to report agent liveness.
type HeartbeatRequest struct {
	AgentId   string `json:"agent_id"`
	Timestamp int64  `json:"timestamp"`
}

// HeartbeatResponse acknowledges a heartbeat.
type HeartbeatResponse struct {
	Acknowledged bool `json:"acknowledged"`
}

// ─── Service Interface ────────────────────────────────────────────────────────

// CheckpointServiceClient is the client API for CheckpointService.
type CheckpointServiceClient interface {
	LdapBind(ctx context.Context, req *LdapBindRequest, opts ...grpc.CallOption) (*LdapBindResponse, error)
	LdapSearch(ctx context.Context, req *LdapSearchRequest, opts ...grpc.CallOption) (*LdapSearchResponse, error)
	LdapCompare(ctx context.Context, req *LdapCompareRequest, opts ...grpc.CallOption) (*LdapCompareResponse, error)
	LdapModify(ctx context.Context, req *LdapModifyRequest, opts ...grpc.CallOption) (*LdapModifyResponse, error)
	VerifyToken(ctx context.Context, req *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	RegisterAgent(ctx context.Context, req *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	AgentHeartbeat(ctx context.Context, req *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

// ─── Client Implementation ────────────────────────────────────────────────────

type checkpointServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewCheckpointServiceClient returns a new CheckpointServiceClient using cc.
func NewCheckpointServiceClient(cc grpc.ClientConnInterface) CheckpointServiceClient {
	return &checkpointServiceClient{cc}
}

func (c *checkpointServiceClient) LdapBind(ctx context.Context, req *LdapBindRequest, opts ...grpc.CallOption) (*LdapBindResponse, error) {
	out := new(LdapBindResponse)
	err := c.cc.Invoke(ctx, "/checkpoint.CheckpointService/LdapBind", req, out, opts...)
	return out, err
}

func (c *checkpointServiceClient) LdapSearch(ctx context.Context, req *LdapSearchRequest, opts ...grpc.CallOption) (*LdapSearchResponse, error) {
	out := new(LdapSearchResponse)
	err := c.cc.Invoke(ctx, "/checkpoint.CheckpointService/LdapSearch", req, out, opts...)
	return out, err
}

func (c *checkpointServiceClient) LdapCompare(ctx context.Context, req *LdapCompareRequest, opts ...grpc.CallOption) (*LdapCompareResponse, error) {
	out := new(LdapCompareResponse)
	err := c.cc.Invoke(ctx, "/checkpoint.CheckpointService/LdapCompare", req, out, opts...)
	return out, err
}

func (c *checkpointServiceClient) LdapModify(ctx context.Context, req *LdapModifyRequest, opts ...grpc.CallOption) (*LdapModifyResponse, error) {
	out := new(LdapModifyResponse)
	err := c.cc.Invoke(ctx, "/checkpoint.CheckpointService/LdapModify", req, out, opts...)
	return out, err
}

func (c *checkpointServiceClient) VerifyToken(ctx context.Context, req *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/checkpoint.CheckpointService/VerifyToken", req, out, opts...)
	return out, err
}

func (c *checkpointServiceClient) RegisterAgent(ctx context.Context, req *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, "/checkpoint.CheckpointService/RegisterAgent", req, out, opts...)
	return out, err
}

func (c *checkpointServiceClient) AgentHeartbeat(ctx context.Context, req *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/checkpoint.CheckpointService/AgentHeartbeat", req, out, opts...)
	return out, err
}
