image:
  repository: icebox-ssh-ca
  tag: "latest"
  pullPolicy: Never

ingress:
  host: icebox.skauswatch.localhost.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
  LOG_LEVEL: "debug"
