[package]
name = "skauswatch-scanner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
clap.workspace = true
fred.workspace = true
metrics.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx = { workspace = true, features = ["postgres"] }
tokio.workspace = true
tokio-rustls.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
yara-x.workspace = true
uuid.workspace = true
thiserror.workspace = true
glob = "=0.3.4"
futures = "=0.3.32"
x509-parser.workspace = true

skauswatch-common.workspace = true
skauswatch-db.workspace = true
skauswatch-streams.workspace = true
skauswatch-telemetry.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile = "=3.27.0"
time.workspace = true
skauswatch-testkit = { workspace = true }

[lints]
workspace = true
