image:
  repository: registry-dal2.penguintech.cloud/skauswatch/icebox-webui
  pullPolicy: Always

ingress:
  host: icebox.skauswatch.penguintech.cloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: icebox-webui-tls
      hosts:
        - icebox.skauswatch.penguintech.cloud

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
