replicaCount: 2

image:
  repository: registry.skauswatch.app/icebox-webui
  pullPolicy: Always

ingress:
  host: icebox.skauswatch.app

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
