{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skauswatch-endpoint-agent.secretName" . }}
  labels:
    {{- include "skauswatch-endpoint-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- toYaml .Values.secretData | nindent 2 }}
{{- end }}
