{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skauswatch-s3scan.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skauswatch-s3scan.labels" . | nindent 4 }}
  {{- $annotations := .Values.serviceAccount.annotations | default dict }}
  {{- if and (eq .Values.awsIdentity.mode "irsa") .Values.awsIdentity.irsa.roleArn }}
  {{- $annotations = merge (dict "eks.amazonaws.com/role-arn" .Values.awsIdentity.irsa.roleArn) $annotations }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
