apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skauswatch-worker-darwin.fullname" . }}-celery
  labels:
    {{- include "skauswatch-worker-darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.celery.replicaCount }}
  selector:
    matchLabels:
      {{- include "skauswatch-worker-darwin.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "skauswatch-worker-darwin.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "skauswatch-worker-darwin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: worker-darwin-celery
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - celery
          - -A
          - workers.celery_app.celery_app
          - worker
          - --loglevel=info
          - -Q
          - darwin_reviews,darwin_plans,darwin_polling
        {{- with .Values.celery.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        env:
        {{- toYaml .Values.env | nindent 12 }}
