apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skauswatch-worker-scanner.fullname" . }}-secret
  labels:
    {{- include "skauswatch-worker-scanner.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- toYaml .Values.secretData | nindent 2 }}
