apiVersion: v1
kind: Secret
metadata:
  name: checkpoint-core-secrets
  labels:
    {{- include "checkpoint-core.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_PASS: {{ .Values.secrets.DB_PASS | b64enc | quote }}
  CHECKPOINT_SIGNING_MEK: {{ .Values.secrets.CHECKPOINT_SIGNING_MEK | b64enc | quote }}
  CHECKPOINT_LICENSE_KEY: {{ .Values.secrets.CHECKPOINT_LICENSE_KEY | b64enc | quote }}
