apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icebox-pki-server.fullname" . }}-secrets
  labels:
    {{- include "icebox-pki-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASS: {{ .Values.secrets.DB_PASS | quote }}
