# Alembic Configuration File
# This file is in the format of PEP 3143 ConfigParser
# http://docs.python.org/library/configparser.html

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)d%%(slug)s_%%(rev)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to zoneinfo.ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field:
# set to 0 to disable zero padding of migration number
# truncate_slug_length = 0

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be treated as revisions in the
# versions/ directory
# sourceless = false

# set to 'true' to treat SQLALCHEMY_DATABASE_URL
# environment variable as case sensitive and pass it
# through as the command line / environment variable
# argument for sqlalchemy.url configuration parameter
# sqlalchemy_url_placeholder = %(DATABASE_URL)s

# Logging configuration
[loggers]
keys = root,sqlalchemy.pool

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.pool]
level = WARN
handlers =
qualname = sqlalchemy.pool

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
