---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: skauswatch-prod

namespace: skauswatch-prod

namePrefix: prod-

labels:
- pairs:
    environment: production
  includeSelectors: false

resources:
- ../../base

replicas:
- name: manager
  count: 3
- name: pki
  count: 3
- name: sshca
  count: 2
- name: monitor
  count: 2
- name: s3scan
  count: 3
- name: scanner
  count: 3
- name: webui
  count: 2

configMapGenerator:
- name: skauswatch-config
  behavior: merge
  literals:
  - LOG_LEVEL=WARN
  - RELEASE_MODE=true

secretGenerator:
- name: skauswatch-secrets
  behavior: merge
  literals:
  - DB_USER=produser
  - DB_PASS=prodpass
  - SECRET_KEY=prodsecretkey
  - SECURITY_PASSWORD_SALT=prodsalt
  - LICENSE_KEY=PENG-PROD-XXXX-XXXX-XXXX-ABCD
  - REDIS_PASSWORD=prodredis
