apiVersion: v1
kind: Namespace
metadata:
  name: skauswatch
  labels:
    name: skauswatch
    app.kubernetes.io/name: skauswatch
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: skauswatch
  annotations:
    description: "SkausWatch Security Monitoring and Alerting System"
    contact: "support@skauswatch.io"