apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: skauswatch
type: Opaque
stringData:
  username: skauswatch
  password: skauswatch-secure-password-2025
  database: skauswatch
