"""
checkpoint-core — inbound gRPC server (CheckpointService).

Called by checkpoint-ldap-agent to authenticate LDAP binds, serve LDAP
searches, verify tokens, and manage agent registrations.

All identity data is fetched from skauswatch-core via CoreIdentityClient —
checkpoint never queries identity tables directly.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone

import grpc
from grpc import aio as grpc_aio
from penguin_dal import DB

from audit.logger import AuditLogger
from checkpoint_grpc.core_client import CoreIdentityClient, CheckpointCoreError

logger = logging.getLogger(__name__)

# ── Protobuf stubs (generated from proto/checkpoint.proto) ────────────────────
# Import lazily — stubs are generated by `make proto`.
try:
    from grpc_generated import checkpoint_pb2, checkpoint_pb2_grpc  # type: ignore[import]

    _STUBS_AVAILABLE = True
except ImportError:
    _STUBS_AVAILABLE = False
    logger.warning(
        "grpc_server.stubs_missing — run 'make proto' to generate gRPC stubs. "
        "The gRPC server will not start until stubs are available."
    )


class CheckpointServicer:
    """
    Implements the CheckpointService gRPC service.

    Each method validates the incoming request, delegates identity lookups
    to CoreIdentityClient, and writes an audit event.
    """

    def __init__(
        self,
        core_client: CoreIdentityClient,
        db: DB,
        audit: AuditLogger,
        ldap_base_dn: str = "dc=skauswatch,dc=app",
    ) -> None:
        self._core = core_client
        self._db = db
        self._audit = audit
        self._base_dn = ldap_base_dn

    # ── LdapBind ──────────────────────────────────────────────────────────────

    async def LdapBind(self, request: "checkpoint_pb2.LdapBindRequest", context: grpc.ServicerContext) -> "checkpoint_pb2.LdapBindResponse":  # noqa: N802
        """
        Authenticate an LDAP bind request from the ldap-agent.

        Validates the DN, extracts username, and delegates to CoreIdentityClient.
        """
        if not _STUBS_AVAILABLE:
            await context.abort(grpc.StatusCode.UNAVAILABLE, "gRPC stubs not generated")

        dn = (request.dn or "").strip()
        agent_id = request.agent_id or "unknown"

        # Extract username from DN — expected format: uid=<username>,ou=users,<base_dn>
        username = _extract_uid_from_dn(dn)
        if not username:
            await self._audit.log(
                "ldap.bind.invalid_dn",
                actor_ip=request.client_ip,
                details={"agent_id": agent_id, "dn": dn},
            )
            return checkpoint_pb2.LdapBindResponse(
                success=False, error="Invalid DN format"
            )

        try:
            user = await self._core.authenticate_user(username, request.password)
        except CheckpointCoreError as exc:
            logger.error("ldap_bind.core_error agent=%s error=%r", agent_id, exc)
            await self._audit.log(
                "ldap.bind.core_error",
                actor_ip=request.client_ip,
                details={"agent_id": agent_id, "error": str(exc)},
            )
            return checkpoint_pb2.LdapBindResponse(
                success=False, error="Identity service unavailable"
            )

        if user is None:
            await self._audit.log(
                "ldap.bind.failed",
                actor_ip=request.client_ip,
                details={"agent_id": agent_id},
            )
            return checkpoint_pb2.LdapBindResponse(
                success=False, error="Invalid credentials"
            )

        await self._audit.log(
            "ldap.bind.success",
            actor_uuid=user.uuid,
            actor_ip=request.client_ip,
            details={"agent_id": agent_id},
        )
        return checkpoint_pb2.LdapBindResponse(success=True, user_uuid=user.uuid)

    # ── LdapSearch ────────────────────────────────────────────────────────────

    async def LdapSearch(self, request: "checkpoint_pb2.LdapSearchRequest", context: grpc.ServicerContext) -> "checkpoint_pb2.LdapSearchResponse":  # noqa: N802
        """
        Serve an LDAP search query.

        Translates LDAP filter to a CoreIdentityClient search and maps
        results back to LDAP entries.
        """
        if not _STUBS_AVAILABLE:
            await context.abort(grpc.StatusCode.UNAVAILABLE, "gRPC stubs not generated")

        agent_id = request.agent_id or "unknown"
        ldap_filter = request.filter or "(objectClass=*)"
        query = _ldap_filter_to_query(ldap_filter)

        try:
            if query:
                users = await self._core.search_users(query)
            else:
                users = await self._core.list_users(page_size=request.size_limit or 100)
        except CheckpointCoreError as exc:
            logger.error("ldap_search.core_error agent=%s error=%r", agent_id, exc)
            return checkpoint_pb2.LdapSearchResponse(error=str(exc))

        requested_attrs = set(request.attributes) if request.attributes else None

        entries = []
        for user in users:
            dn = f"uid={user.username},ou=users,{self._base_dn}"
            attrs = _user_to_ldap_attributes(user, requested_attrs)
            entries.append(checkpoint_pb2.LdapEntry(dn=dn, attributes=attrs))

        return checkpoint_pb2.LdapSearchResponse(entries=entries)

    # ── LdapCompare ───────────────────────────────────────────────────────────

    async def LdapCompare(self, request: "checkpoint_pb2.LdapCompareRequest", context: grpc.ServicerContext) -> "checkpoint_pb2.LdapCompareResponse":  # noqa: N802
        """Compare an attribute value in an LDAP entry."""
        if not _STUBS_AVAILABLE:
            await context.abort(grpc.StatusCode.UNAVAILABLE, "gRPC stubs not generated")

        username = _extract_uid_from_dn(request.dn)
        if not username:
            return checkpoint_pb2.LdapCompareResponse(matches=False, error="Invalid DN")

        try:
            users = await self._core.search_users(username)
            user = next((u for u in users if u.username == username), None)
        except CheckpointCoreError as exc:
            return checkpoint_pb2.LdapCompareResponse(matches=False, error=str(exc))

        if user is None:
            return checkpoint_pb2.LdapCompareResponse(matches=False, error="Entry not found")

        attr_map = {
            "mail": user.email,
            "uid": user.username,
            "cn": user.display_name,
            "displayName": user.display_name,
        }
        actual = attr_map.get(request.attribute, "")
        return checkpoint_pb2.LdapCompareResponse(matches=(actual == request.value))

    # ── LdapModify ────────────────────────────────────────────────────────────

    async def LdapModify(self, request: "checkpoint_pb2.LdapModifyRequest", context: grpc.ServicerContext) -> "checkpoint_pb2.LdapModifyResponse":  # noqa: N802
        """
        Handle LDAP modify operations.

        Checkpoint is read-only for identity data — writes are rejected with
        an LDAP unwillingToPerform error code to inform the client.
        """
        if not _STUBS_AVAILABLE:
            await context.abort(grpc.StatusCode.UNAVAILABLE, "gRPC stubs not generated")

        await self._audit.log(
            "ldap.modify.rejected",
            details={
                "dn": request.dn,
                "agent_id": request.agent_id,
                "reason": "checkpoint is read-only; modify identity via skauswatch-core",
            },
        )
        return checkpoint_pb2.LdapModifyResponse(
            success=False,
            error="unwillingToPerform: checkpoint identity data is read-only",
        )

    # ── VerifyToken ───────────────────────────────────────────────────────────

    async def VerifyToken(self, request: "checkpoint_pb2.VerifyTokenRequest", context: grpc.ServicerContext) -> "checkpoint_pb2.VerifyTokenResponse":  # noqa: N802
        """
        Verify an OAuth2 access token issued by checkpoint-core.

        Checks the checkpoint_tokens table for the token, validates expiry,
        and returns claims.
        """
        if not _STUBS_AVAILABLE:
            await context.abort(grpc.StatusCode.UNAVAILABLE, "gRPC stubs not generated")

        import hashlib

        token_hash = hashlib.sha256(request.token.encode()).hexdigest()
        now = datetime.now(tz=timezone.utc).replace(tzinfo=None)

        row = self._db(
            (self._db.checkpoint_tokens.token_hash == token_hash)
            & (self._db.checkpoint_tokens.token_type == "access")
        ).select().first()

        if row is None:
            return checkpoint_pb2.VerifyTokenResponse(valid=False, error="Token not found")

        if row.revoked_at is not None:
            return checkpoint_pb2.VerifyTokenResponse(valid=False, error="Token revoked")

        if row.expires_at < now:
            return checkpoint_pb2.VerifyTokenResponse(valid=False, error="Token expired")

        if request.client_id and row.client_id != request.client_id:
            return checkpoint_pb2.VerifyTokenResponse(
                valid=False, error="Client ID mismatch"
            )

        expires_epoch = int(row.expires_at.replace(tzinfo=timezone.utc).timestamp())
        return checkpoint_pb2.VerifyTokenResponse(
            valid=True,
            user_uuid=row.user_uuid or "",
            scopes=row.scopes or "",
            expires_at=expires_epoch,
        )

    # ── RegisterAgent ─────────────────────────────────────────────────────────

    async def RegisterAgent(self, request: "checkpoint_pb2.RegisterAgentRequest", context: grpc.ServicerContext) -> "checkpoint_pb2.RegisterAgentResponse":  # noqa: N802
        """Accept a registration request from an ldap-agent."""
        if not _STUBS_AVAILABLE:
            await context.abort(grpc.StatusCode.UNAVAILABLE, "gRPC stubs not generated")

        logger.info(
            "agent.registered agent_id=%s hostname=%s version=%s site=%s",
            request.agent_id,
            request.hostname,
            request.version,
            request.site_name,
        )
        await self._audit.log(
            "agent.registered",
            details={
                "agent_id": request.agent_id,
                "hostname": request.hostname,
                "version": request.version,
                "site_name": request.site_name,
            },
        )
        return checkpoint_pb2.RegisterAgentResponse(success=True)

    # ── AgentHeartbeat ────────────────────────────────────────────────────────

    async def AgentHeartbeat(self, request: "checkpoint_pb2.HeartbeatRequest", context: grpc.ServicerContext) -> "checkpoint_pb2.HeartbeatResponse":  # noqa: N802
        """Acknowledge a heartbeat from an ldap-agent."""
        if not _STUBS_AVAILABLE:
            await context.abort(grpc.StatusCode.UNAVAILABLE, "gRPC stubs not generated")

        logger.debug("agent.heartbeat agent_id=%s status=%s", request.agent_id, request.status)
        return checkpoint_pb2.HeartbeatResponse(ok=True)


# ── gRPC server lifecycle ─────────────────────────────────────────────────────


async def start_grpc_server(
    core_client: CoreIdentityClient,
    db: DB,
    audit: AuditLogger,
    port: int = 50051,
    ldap_base_dn: str = "dc=skauswatch,dc=app",
) -> grpc_aio.Server | None:
    """
    Create and start the async gRPC server.

    Returns the running Server instance, or None if stubs are unavailable.
    """
    if not _STUBS_AVAILABLE:
        logger.error(
            "grpc_server.start_failed — checkpoint_pb2_grpc not found. "
            "Run 'make proto' to generate stubs."
        )
        return None

    servicer = CheckpointServicer(core_client, db, audit, ldap_base_dn)
    server = grpc_aio.server()
    checkpoint_pb2_grpc.add_CheckpointServiceServicer_to_server(servicer, server)
    listen_addr = f"[::]:{port}"
    server.add_insecure_port(listen_addr)
    await server.start()
    logger.info("grpc_server.started port=%d", port)
    return server


# ── Helpers ───────────────────────────────────────────────────────────────────


def _extract_uid_from_dn(dn: str) -> str | None:
    """
    Extract the uid value from an LDAP DN.

    Expects: uid=<username>,ou=users,...
    Returns None if the DN does not match the expected format.
    """
    parts = dn.split(",")
    for part in parts:
        part = part.strip()
        if part.lower().startswith("uid="):
            return part[4:].strip()
    return None


def _ldap_filter_to_query(ldap_filter: str) -> str:
    """
    Extract a search term from a simple LDAP filter.

    Supports: (uid=foo), (mail=foo*), (cn=foo*), (objectClass=*) → ""
    Returns an empty string for wildcard/objectClass filters.
    """
    import re

    # Strip outer parens
    inner = ldap_filter.strip().lstrip("(").rstrip(")")
    # Simple equality / prefix: attribute=value or attribute=value*
    match = re.match(r"^(uid|mail|cn|sn|displayName)=([^*]+)\*?$", inner, re.IGNORECASE)
    if match:
        return match.group(2).strip()
    return ""


def _user_to_ldap_attributes(
    user: "CoreIdentityClient",  # actually UserRecord but avoids circular import
    requested: set[str] | None,
) -> list["checkpoint_pb2.LdapAttribute"]:
    """Map a UserRecord to a list of LdapAttribute proto messages."""
    if not _STUBS_AVAILABLE:
        return []

    all_attrs: dict[str, list[str]] = {
        "objectClass": ["inetOrgPerson", "organizationalPerson", "person", "top"],
        "uid": [user.username],
        "mail": [user.email],
        "cn": [user.display_name],
        "displayName": [user.display_name],
        "sn": [user.display_name.split()[-1] if user.display_name else ""],
        "givenName": [user.display_name.split()[0] if user.display_name else ""],
        "memberOf": user.groups,
    }

    result = []
    for attr_type, values in all_attrs.items():
        if requested is None or attr_type in requested:
            if values and any(v for v in values):
                result.append(
                    checkpoint_pb2.LdapAttribute(type=attr_type, values=values)
                )
    return result
