---
apiVersion: v1
kind: Service
metadata:
  name: pki
  namespace: skauswatch
  labels:
    app.kubernetes.io/name: pki
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pki
  ports:
  - name: http
    port: 5001
    targetPort: 5001
    protocol: TCP
