apiVersion: v1
kind: Service
metadata:
  name: icebox-webui
  namespace: icebox
  labels:
    app.kubernetes.io/name: icebox-webui
    app.kubernetes.io/part-of: icebox
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: icebox-webui
